; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

global file_name_source := ""
global ffmpeg_proxy := ""
global ffmpeg_trans := ""
global ffmpeg_resize := ""
global ffmpeg_target := ""

Gui Add, Text, x25 y15 w120 h23 +0x200, File To Process:
Gui Add, Edit, x23 y53 w741 h34 vedit_filename

Gui Font, Bold
Gui Add, Button, gRun_ffmpeg x641 y97 w121 h41, &Run
Gui Font
Gui Add, DropDownList, x26 y102 w578 vffmpegRunType, Proxy With Timecode||Transocode to ProRes LT|Resize to 1920x1080
Gui Add, Button, gBrowseFiles x663 y12 w97 h34, &Browse

Gui Show, w784 h154, File ffmpeg Runner
Return

Run_ffmpeg(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
GuiControlGet, ffmpegRunType
;MsgBox, Selected: %ffmpegRunType%

	if instr(ffmpegRunType,"Proxy")
		{
		;MsgBox, "Proxy"
		;* add TIMECODE
		;StringReplace, ffmpeg_target,file_name_source,".avi","_proxy.avi", All
		;StringReplace, ffmpeg_target,file_name_source,".mp4","_proxy.mp4", All
		;StringReplace, ffmpeg_target,file_name_source,".mov","_proxy.mov", All
		ffmpeg_target := StrReplace(file_name_source,".avi","_TLproxy.avi")
        ffmpeg_target := StrReplace(ffmpeg_target,".mkv","_TLproxy.mkv")
		ffmpeg_target := StrReplace(ffmpeg_target,".mp4","_TLproxy.mp4")
		ffmpeg_target := StrReplace(ffmpeg_target,".mov","_TLproxy.mov")
		ffmpeg_proxy := "ffmpeg -i " . file_name_source . " -vf  ""drawtext=text='%{pts\:hms}':fontfile=tahoma.ttf:fontsize=48:fontcolor=white:box=1:boxborderw=6:boxcolor=black@0.75:x=(w-text_w)/2:y=h-text_h-20"" -c:v libx264 -preset veryfast -pix_fmt yuv420p -c:a aac " . ffmpeg_target
		msgbox %ffmpeg_proxy%
		RunWait, %comspec% /k %ffmpeg_proxy%
		}
	else if instr(ffmpegRunType,"Trans")
		{
		MsgBox, "Trans"
		}
	else if instr(ffmpegRunType,"Resize")
		{
		MsgBox, "Resize"
		}

}

BrowseFiles(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

GuiDropFiles:
GuiControl,,edit_filename,%A_GuiEvent% 
file_name_source := A_GuiEvent
Return

GuiEscape:
GuiClose:
    ExitApp
