; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

; globals
;xTL :=0
;yTL :=0
;xBR :=0
;yBR :=0

global TL_x :=0, TL_y :=0, BR_x :=0, BR_y :=0, ThisWin_H, ThisWin_W
global CMDffplay :="ffplay..."
global CMDffmpeg_capwaudio := "ffmpeg"
global MyDevicesDLL :=""

Gui Font, Bold, Courier New
Gui Add, Button, x-1 y1 w224 h25 gGetTopLeft, Get TOP LEFT Position

Gui Add, Text, x17 y41 w120 h23 +0x200, ffplay (test)
Gui Add, Edit, x15 y76 w520 h75 vEdit_ffplay

Gui Add, Text, x17 y153 w178 h23 +0x200, ffmpeg (to capture)
Gui Add, Edit, x15 y193 w520 h75 vEdit_ffmpeg

Gui Add, Button, x446 y284 w80 h40 gQuit, E&xit
Gui Add, Button, x15 y284 w89 h40 gCMDffplay, Run ffplay
Gui Add, Button, x120 y284 w97 h40 gCMDffmpeg, Run ffmpeg

ListDevices := ""
Gui, Add, DropDownList, x15 y330 w300 vMyDevicesDLL ;, %ListDevices% 
Gui Add, Button, x350 y330 w150 h20 gCMDload_devices, Load Audio Devices

Gui Font
Gui Font, Bold, Courier New
Gui Add, Button, x265 y370 w300 h25 gGetBottomRight, Get BOTTOM RIGHT Position
Gui Font

Gui Show, w600 h400, ffmpegGUI
Return

GuiEscape:
GuiClose:
    ExitApp


; ******** FUNCTIONS **************
GetTopLeft:
; this works if Gui named "ffmpegGUI" and then WinGetPos Called this way
WinGetPos, x, y, w, h, ffmpegGUI
;global xTL
;global yTL
TL_x := x
TL_y := y
ThisWin_H := h
ThisWin_W := w
Clipboard := "-offset_x " TL_x " -offset_y " TL_y ;"this win width: " w "this win height: " h
; -video_size " w "x" h
GuiControl,,Edit_ffplay,%Clipboard%
return

;*** --- GetBottomRight --- ***
GetBottomRight:
; this works if Gui named "ffmpegGUI" and then WinGetPos Called this way
WinGetPos, x, y, w, h, ffmpegGUI

BR_x := x+ThisWin_W
BR_y := y+ThisWin_H+8 ; 14 roughly works

; Will need to FIX, account for, screen magnification
CapWin_Height := round(((BR_y - TL_y))-8)
CapWin_Width := round((BR_x - TL_x))

; *** Create ffplay command
CMDffplay := "ffplay -f gdigrab -framerate 30 -show_region 1 -i desktop -offset_x " TL_x " -offset_y " TL_y " -video_size " CapWin_Width  "x" CapWin_Height
;Clipboard := "-offset_x " TL_x " -offset_y " TL_y " -video_size " CapWin_Width  "x" CapWin_Height
; -video_size " w "x" h
GuiControl,,Edit_ffplay,%CMDffplay% ;%Clipboard%

guicontrolget, MyDevicesDLL_selected,, MyDevicesDLL
;msgbox %MyDevicesDLL_selected%
;*** Create ffmpeg command
CMDffmpeg_capwaudio := "ffmpeg -f gdigrab -offset_x " TL_x " -offset_y " TL_y " -video_size " CapWin_Width  "x" CapWin_Height " -i desktop -f dshow -i audio=" MyDevicesDLL_selected " -c:v libx264 -preset veryfast -pix_fmt yuv420p -vf ""scale=1920x1080"" -y " a_scriptdir "\atest_capture.mp4"
GuiControl,,Edit_ffmpeg,%CMDffmpeg_capwaudio% ;%Clipboard%

return

;*** --- CMDffplay ---***
CMDffplay:
;msgbox "here" %CMD%  ' ,,min = minimize cmd prompt
Run, %comspec% /c %CMDffplay%,,min
Return

;*** --- CMDffmpeg ---***
CMDffmpeg:
;msgbox "here" %CMD%
RunWait, %comspec% /k %CMDffmpeg_capwaudio%
Return

CMDload_devices:
GuiControl,, MyDevicesDLL, |%ListDevices% ; this will overwrite the choices in the list with the same values, effectively 're-setting' it to have nothing selected
DDLCount := 0
Run, %comspec% /c ffmpeg -list_devices true -f dshow -i dummy -hide_banner 2> mydevices.txt
sleep 2000
FileRead, Contents, mydevices.txt
	loop,parse,contents,`n, `r
  {
  textline := InStr(A_LoopField,"(video)") + InStr(A_LoopField,"(audio)")
        ;msgbox Textline: %textline% 
        if textline > 0
        {
        OutputVar := RegExMatch(A_LoopField, """.+.?""",var1)
        ; if I want to remove quotes "
        ;StringReplace, var1,var1,`", , All 
            if DDLCount = 0
            {
            ; if first, we want first item selected with ||
            GuiControl,, MyDevicesDLL, %  var1 "||"
            DDLCount = DDLCount + 1
            }
            else
            {
            GuiControl,, MyDevicesDLL, %  var1 "|"
            }
        ;MsgBox, %OutputVar% & %var1%
        }
  }
return

Quit(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
ExitApp

}


; ************** NOTES ******************
;ffplay -f gdigrab -framerate 24 -offset_x 1889 -offset_y 503 -video_size 1720x955 -show_region 1 -i desktop

; *** Capture with audio
;ffmpeg -f gdigrab -offset_x 1200 -offset_y 190 -video_size 2578x1449 -i desktop -f dshow -i audio="In 1-2 (MOTU M Series)" -c:v libx264 -preset veryfast -pix_fmt yuv420p -vf "scale=1920x1080" -y s002_window_capture.mp4

