; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

global winTitle
winTitle := "ahk_class ConsoleWindowClass"

Gui Add, Edit, vEdtValue x59 y44 w479 h152
Gui Add, Button, gTest1 x65 y383 w116 h55, &Test1
Gui Add, Button, gTest2 x199 y385 w87 h52, &Test2
Gui Add, Button, gCapture x302 y384 w119 h51, &Capture
Gui Add, Button, gStop x437 y385 w92 h55, &Stop
Gui Add, Edit, vMyStatus x70 y231 w464 h115

Gui Show, w606 h515, Test ffmpeg webcam capture
Return

Test1(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

Test2(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

Capture(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
app      := "C:\Max_Software\ffmpeg_basic\ffmpeg.exe"
vid      := "Elgato Facecam" ; Depends on your camera
codec    := "mjpeg"                ; Depends on your camera
cLine    := " -f dshow -video_size 1280x720 -rtbufsize 702000k -framerate 30 -i video=""" vid """"
          . " -r 30 -threads 4 -vcodec " codec " -crf 0 -preset ultrafast -f mpegts "
out      := A_ScriptDir "\video.mkv"
winTitle := "ahk_class ConsoleWindowClass" ; GLOBAL

FileRecycle % out
Run % app cLine out

}

Stop(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
   msgbox "This should stop it if winTitle exists"
if WinExist(winTitle)
    {
    msgbox "winTitle Found"
    WinActivate
    Send q
    WinWaitClose
    Run % out
    }
}

GuiEscape:
GuiClose:
    ExitApp
